server:
  port: 8088
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://34.134.189.180:5432/escuela
    username: postgres
    password: GJ-CMrb3)$lDPLk.